// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9ASxgmxi6xcwih004kbvj-9Ur5OwK40',
    appId: '1:487077094397:web:560ab0cac0bfecbe14af94',
    messagingSenderId: '487077094397',
    projectId: 'gemicates-30d56',
    authDomain: 'gemicates-30d56.firebaseapp.com',
    storageBucket: 'gemicates-30d56.appspot.com',
    measurementId: 'G-ZP3W0VTQNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3u6TgxsqrEm9W1yY1iKKgjD4D3Paj2_Y',
    appId: '1:487077094397:android:e18bac6519131c0414af94',
    messagingSenderId: '487077094397',
    projectId: 'gemicates-30d56',
    storageBucket: 'gemicates-30d56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2vCn-G3IrIMklJMkw4kOyuCJ8ZMWT9u8',
    appId: '1:487077094397:ios:3f2668ffd03475b914af94',
    messagingSenderId: '487077094397',
    projectId: 'gemicates-30d56',
    storageBucket: 'gemicates-30d56.appspot.com',
    iosBundleId: 'com.example.gemicatesMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2vCn-G3IrIMklJMkw4kOyuCJ8ZMWT9u8',
    appId: '1:487077094397:ios:3f2668ffd03475b914af94',
    messagingSenderId: '487077094397',
    projectId: 'gemicates-30d56',
    storageBucket: 'gemicates-30d56.appspot.com',
    iosBundleId: 'com.example.gemicatesMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9ASxgmxi6xcwih004kbvj-9Ur5OwK40',
    appId: '1:487077094397:web:4320e42d3d089c8e14af94',
    messagingSenderId: '487077094397',
    projectId: 'gemicates-30d56',
    authDomain: 'gemicates-30d56.firebaseapp.com',
    storageBucket: 'gemicates-30d56.appspot.com',
    measurementId: 'G-R4SN3HXX77',
  );
}
